# mysql 相关的配置  (yao_blog)
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yao_blog?useSSL=false    # useSSL=false 正式环境下还是提供证书比较好,毕竟安全第一
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


# mybatis 分页插件相关配置
pagehelper:
  # 指定数据库类型
  helper-dialect: mysql
  # 分页参数合理化,默认false禁用;启用时,如果pageNum<1会查询第一页,pageNum>pages会查询最后一页;
  #                           不启用时:如果pageNum<1或pageNum>pages会返回空数据;
  reasonable: true
  # 默认值false;分页插件会从查询方法的参数值中,自动根据上面 params 配置的字段中取值,查找到合适的值时就会自动分页
  support-methods-arguments: true
  # 用于从对象中根据属性名取值;可以配置 pageNum,pageSize,count,pageSizeZero,reasonable,不配置映射的用默认值;
  # 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  params: count=countSql
  # 默认值为false,使用默认值时不需要增加该配置;设为true时,需要配置该参数。
  # 当该参数设置为true时,如果pageSize=0或者RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询,但是返回结果仍然是Page类型）.
  page-size-zero: true